### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by bellanz80** [jbp35/layout_panel#1]
Hi. Windows 10, QGIs 3.20.3, new profile
When i install the plug, an error message appears

No se pudo cargar el complemento 'layout_panel-main' debido a un error al llamar a su método classFactory() 

ModuleNotFoundError: No module named 'resources_rc' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\nuovo/python/plugins\layout_panel-main\__init__.py", line 35, in classFactory
    from .layout_panel import LayoutPanel
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\nuovo/python/plugins\layout_panel-main\layout_panel.py", line 31, in 
    from .layout_panel_dockwidget import LayoutPanelDockWidget
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\nuovo/python/plugins\layout_panel-main\layout_panel_dockwidget.py", line 32, in 
    FORM_CLASS, _ = uic.loadUiType(os.path.join(
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 77, in 
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'resources_rc'

Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión de QGIS: 3.20.3-Odense Odense, 495fbaec 

Ruta de Python:
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\nuovo/python
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\nuovo/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.20.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.20.3\bin
C:\Users\Luca\AppData\Roaming\Python\Python39\site-packages
C:\Users\Luca\AppData\Roaming\Python\Python39\site-packages\win32
C:\Users\Luca\AppData\Roaming\Python\Python39\site-packages\win32\lib
C:\Users\Luca\AppData\Roaming\Python\Python39\site-packages\Pythonwin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\nuovo/python

**Comment by jbp35** [comment]
Hi, could you please try to update to the new version of the plugin v0.2 ? The issue should be fixed now. Thanks,

**Comment by bellanz80** [comment]
Yes, thank`s!
