### ISSUE TITLE
ANOTHER INSTALL ERROR

### ISSUE THREAD

**Issue by bwmoths** [jbp35/layout_panel#2]
On attempting to install the Layout Panel Plugin on QGIS 3.20.3 I get the following error -

Couldn't load plugin 'layout_panel-main' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'resources_rc' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\layout_panel-main\__init__.py", line 35, in classFactory
    from .layout_panel import LayoutPanel
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\layout_panel-main\layout_panel.py", line 31, in 
    from .layout_panel_dockwidget import LayoutPanelDockWidget
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\layout_panel-main\layout_panel_dockwidget.py", line 32, in 
    FORM_CLASS, _ = uic.loadUiType(os.path.join(
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 77, in 
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'resources_rc'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.3-Odense Odense, 495fbaec 

Python Path:
C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TomBio
C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:\Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\dms_2_deg
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS32~1.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\PROGRA~1\QGIS32~1.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/marti/AppData/Roaming/QGIS/QGIS3\profiles\default/python
F:/GIS/Non-UKProjects/EUROPE Alien Species

**Comment by bwmoths** [comment]
Whilst reporting this install error it seems a fix for the existing install error has appeared which has fixed my problem !!!!!

**Comment by jbp35** [comment]
Thanks, glad to know the fix solved this issue.
